CREATE TABLE Users (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    FirstName VARCHAR(100) NOT NULL ,
    LastName VARCHAR(100) NOT NULL,
    Email VARCHAR(255) NOT NULL UNIQUE,
    Password VARCHAR(255) NOT NULL
);

CREATE TABLE Posts (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    PostTimeStamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PostText TEXT NOT NULL,
    UserId INT,
    FOREIGN KEY (UserId) REFERENCES Users(Id)
);

SELECT * FROM Users WHERE Email = 'Tyriquedebruin@gmail.com';